### ISSUE TITLE
Configuring esbuild for bundling classes issue

### ISSUE THREAD

**Issue by joshbrew** [godotjs/javascript#178]
I've been piecing together how to use this API from the main guide (the older examples won't load the jsx files) and I am having an issue bundling through esbuild which was used in some of the examples, albeit an older version. For whatever reason, esbuild recompiles the class syntax and then the ECMAscript interpreter can't recognize it. If I just reformat back then it works again, but this rules out bundling in my current config:

Before bundling:
<img width="469" alt="281287424-833c3c45-7f1a-419d-b236-0447e1531b8f" src="https://github.com/Geequlim/ECMAScript/assets/18196383/fb1d1902-2de2-430c-89d1-f60819e76e47">

After bundling:
<img width="449" alt="281287335-a05b0f0f-c205-4f65-a3b1-69635cc984f5" src="https://github.com/Geequlim/ECMAScript/assets/18196383/617e6685-5062-4e18-b7de-8a63e680c0e2">

So the top works, the bottom doesn't. What esbuild versions are you using or are there some special settings to use to prevent this? Otherwise it's just an esm compilation.

In the examples, the esbuild compilation still preseves the `class x` syntax instead of this odd var x = class { which anonymizes the class itself. This seems to be innate to esbuild.

**Comment by joshbrew** [comment]
Okay the issue is as of 0.7.19 of esbuild, but it's for performance reasons https://github.com/evanw/esbuild/blob/main/CHANGELOG-2020.md#0719

May be worth fixing compatibility for this syntax in ECMAscript

**Comment by nmerget** [comment]
You can check [this](https://github.com/fukaraadam-workspace/godot-js-template) repo or [this](https://github.com/nmerget/gott) repo. Both work with the current editor with different `esbuild` settings.

**Comment by nmerget** [comment]
There is a new recommnded way for using TypeScript and GodotJS: https://godotjs.github.io/documentation/typescript/intro

[`godot-ts`](https://github.com/godotjs/godot-ts) will bundle a working `esbuild` to generate your files and handle some edge-cases
