### ISSUE TITLE
export { default } from xxx lead to a crash

### ISSUE THREAD

**Issue by AsakuraMizu** [godotjs/javascript#59]
Example:  
a.js
```js
export default class A extends godot.Node {
}
```

b.js
```js
export { default } from './a';
```

And this will also crash:  
c.js
```js
export class C extends godot.Node {
}
```

d.js
```js
export { C as default } from './c';
```

**Comment by Geequlim** [comment]
Does `default` is a keyword to prevent you doing this ?

**Comment by jcostello** [comment]
@AsakuraMizu I think you can't use 'default' in case b.js and d.js. Its a keyword

**Comment by nmerget** [comment]
Your examples aren't valid. Check [this](https://stackoverflow.com/questions/39282253/how-can-i-alias-a-default-import-in-javascript) for more information.
